trigger:
- main
- master

variables:
  # Azure service connection established during pipeline creation
  azureSubscription: 'arm-fin-costmgt-predev'
  appName: 'cdmutil-fin-costmgt-predev'
  appType: 'functionApp'
  # Agent VM image name
  vmImageName: 'windows-latest'
  projPath: 'Analytics/CDMUtilSolution/CDMUtil_AzureFunctions'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  pool:
    vmImage: windows-latest # Use 'windows-latest' if you have Windows native +Node modules
    name: "Azure Pipelines"
  jobs:
  - job: BuildJob
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore'
      inputs:
        command: 'restore'
        projects: $(projPath)
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: $(projPath)
        arguments: '--configuration $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        projects: $(projPath)
        publishWebProjects: False
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'

- stage: Deploy
  pool:
    vmImage: windows-latest # Use 'windows-latest' if you have Windows native +Node modules
    name: vmss-ado-hub-predev
  jobs:
  - job: DeployToAzure
    steps:
    - download: current  # Download Artifacts to current host
      artifact: drop
    - task: AzureFunctionApp@1 # Add this at the end of your file
      inputs:
        azureSubscription: $(azureSubscription)
        appType: $(appType) # default is functionApp
        appName: $(appName)
        package: $(Pipeline.Workspace)/drop/*.zip
